// Mock conversations data with simplified color labels
export const mockConversations = [
  {
    id: "conv1",
    name: "John Smith",
    phone: "+1 (555) 123-4567",
    lastMessage: "I would like to inquire about your product pricing",
    timestamp: "2023-06-15T10:30:00Z",
    unread: 3,
    status: "online",
    isBusinessAccount: true,
    labels: ["Customer", "VIP"],
    colorLabel: "potential",
    assignedTo: "agent1",
    botActive: true,
  },
  {
    id: "conv2",
    name: "Maria Garcia",
    phone: "+1 (555) 234-5678",
    lastMessage: "Thanks for the information!",
    timestamp: "2023-06-15T09:45:00Z",
    unread: 0,
    status: "offline",
    isBusinessAccount: false,
    labels: ["Lead"],
    colorLabel: "new",
    assignedTo: "agent2",
    botActive: true,
  },
  {
    id: "conv3",
    name: "Tech Solutions Inc.",
    phone: "+1 (555) 345-6789",
    lastMessage: "We are interested in your enterprise plan",
    timestamp: "2023-06-15T08:20:00Z",
    unread: 1,
    status: "typing",
    isBusinessAccount: true,
    labels: ["Business", "Enterprise"],
    colorLabel: "followup",
    assignedTo: "agent1",
    botActive: true,
  },
  {
    id: "conv4",
    name: "Robert Johnson",
    phone: "+1 (555) 456-7890",
    lastMessage: "When will my order be delivered?",
    timestamp: "2023-06-14T16:50:00Z",
    unread: 0,
    status: "offline",
    isBusinessAccount: false,
    labels: ["Customer"],
    colorLabel: "",
    assignedTo: "agent3",
    botActive: true,
  },
  {
    id: "conv5",
    name: "Sarah Williams",
    phone: "+1 (555) 567-8901",
    lastMessage: "I need help with my recent purchase",
    timestamp: "2023-06-14T14:30:00Z",
    unread: 2,
    status: "offline",
    isBusinessAccount: false,
    labels: ["Support"],
    colorLabel: "new",
    assignedTo: "agent2",
    botActive: true,
  },
  {
    id: "conv6",
    name: "Global Retail Ltd.",
    phone: "+1 (555) 678-9012",
    lastMessage: "Can we schedule a demo next week?",
    timestamp: "2023-06-14T11:15:00Z",
    unread: 0,
    status: "offline",
    isBusinessAccount: true,
    labels: ["Business", "Lead"],
    colorLabel: "potential",
    assignedTo: "agent1",
    botActive: true,
  },
]

// Define available color labels (simplified)
export const colorLabels = [
  { id: "all", name: "All", color: "gray" },
  { id: "new", name: "New", color: "green" },
  { id: "followup", name: "Follow-up", color: "yellow" },
  { id: "potential", name: "Potential", color: "orange" },
]

// Mock messages data
export const mockMessages = [
  // Conversation 1
  {
    id: "msg1",
    conversationId: "conv1",
    content: "Hello, I am interested in your products. Can you tell me more about pricing?",
    timestamp: "2023-06-15T10:25:00Z",
    status: "read",
    sender: "them",
    type: "text",
  },
  {
    id: "msg2",
    conversationId: "conv1",
    content: "Hi! Thank you for your interest. Our pricing starts at $29/month for the basic plan.",
    timestamp: "2023-06-15T10:27:00Z",
    status: "read",
    sender: "me",
    type: "text",
  },
  {
    id: "msg3",
    conversationId: "conv1",
    content: "What features are included in the basic plan?",
    timestamp: "2023-06-15T10:28:00Z",
    status: "read",
    sender: "them",
    type: "text",
  },
  {
    id: "msg4",
    conversationId: "conv1",
    content: "The basic plan includes 5 users, 10GB storage, and access to core features. Here is our brochure:",
    timestamp: "2023-06-15T10:29:00Z",
    status: "read",
    sender: "me",
    type: "text",
  },
  {
    id: "msg5",
    conversationId: "conv1",
    content: "/placeholder.svg?height=400&width=300",
    timestamp: "2023-06-15T10:29:30Z",
    status: "read",
    sender: "me",
    type: "image",
    fileName: "pricing_brochure.jpg",
    fileSize: "1.2 MB",
  },
  {
    id: "msg6",
    conversationId: "conv1",
    content: "I would like to inquire about your product pricing",
    timestamp: "2023-06-15T10:30:00Z",
    status: "delivered",
    sender: "them",
    type: "text",
  },
  {
    id: "msg7",
    conversationId: "conv1",
    content: "product_catalog.pdf",
    timestamp: "2023-06-15T10:31:00Z",
    status: "delivered",
    sender: "them",
    type: "file",
    fileName: "product_catalog.pdf",
    fileSize: "3.5 MB",
  },

  // Conversation 2
  {
    id: "msg8",
    conversationId: "conv2",
    content: "Hi, I saw your ad online and wanted to learn more about your services.",
    timestamp: "2023-06-15T09:30:00Z",
    status: "read",
    sender: "them",
    type: "text",
  },
  {
    id: "msg9",
    conversationId: "conv2",
    content:
      "Hello Maria! We offer a range of digital marketing services. What specific services are you interested in?",
    timestamp: "2023-06-15T09:35:00Z",
    status: "read",
    sender: "me",
    type: "text",
  },
  {
    id: "msg10",
    conversationId: "conv2",
    content: "I am mainly interested in SEO services for my small business website.",
    timestamp: "2023-06-15T09:40:00Z",
    status: "read",
    sender: "them",
    type: "text",
  },
  {
    id: "msg11",
    conversationId: "conv2",
    content: "/placeholder.svg?height=300&width=500",
    timestamp: "2023-06-15T09:42:00Z",
    status: "read",
    sender: "them",
    type: "image",
    fileName: "my_website.jpg",
    fileSize: "0.8 MB",
  },
  {
    id: "msg12",
    conversationId: "conv2",
    content:
      "Great! Our SEO packages start at $499/month and include keyword research, on-page optimization, and monthly reporting.",
    timestamp: "2023-06-15T09:43:00Z",
    status: "read",
    sender: "me",
    type: "text",
  },
  {
    id: "msg13",
    conversationId: "conv2",
    content: "seo_proposal.pdf",
    timestamp: "2023-06-15T09:44:00Z",
    status: "read",
    sender: "me",
    type: "file",
    fileName: "seo_proposal.pdf",
    fileSize: "2.1 MB",
  },
  {
    id: "msg14",
    conversationId: "conv2",
    content: "Thanks for the information!",
    timestamp: "2023-06-15T09:45:00Z",
    status: "read",
    sender: "them",
    type: "text",
  },
]

